name: RDP + Tailscale + RustDesk + GoLogin

on:
  workflow_dispatch:
    inputs:
      ts_authkey:         { description: "Tailscale Auth key (reusable or ephemeral)", required: true }
      quick_test:         { description: "Run 5-minute test", type: boolean, default: false }
      runtime_minutes:    { description: "Runtime (max 360; default 355 when not test)", required: false, default: "355" }
      do_purge:           { description: "Purge bullet* devices at start (single instance only)", required: false, default: "true" }
      cycles:             { description: "0=stop after this run; N=handoffs left incl this run", required: false, default: "0" }
      rdp_count:          { description: "How many RDP instances (1-10) [ignored if CRD provided]", required: false, default: "1" }
      crd_code:
        description: >-
          Paste raw CRD code (4/0AV...), full PowerShell command, or text/URL containing --code="4/...".
          If provided -> single instance; CRD launches first.
        required: false
        default: ""
      crd_pin:
        description: "CRD PIN (6–12 digits). Used when launching CRD to avoid interactive prompt."
        required: false
        default: "123456"

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: pwsh

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.mk.outputs.matrix }}
      multi:  ${{ steps.mk.outputs.multi }}
    steps:
      - id: mk
        run: |
          $crd = @'
          ${{ inputs.crd_code }}
          '@.Trim()

          if ($crd.Length -gt 0) { $n = 1 } else {
            $n = [int]"${{ inputs.rdp_count }}"; if ($n -lt 1) { $n = 1 }; if ($n -gt 10) { $n = 10 }
          }

          $inc = @(); for ($i=1; $i -le $n; $i++){ $inc += @{ id = $i } }
          $json = @{ include = $inc } | ConvertTo-Json -Compress
          "matrix=$json" | Out-File $env:GITHUB_OUTPUT -Append -Encoding utf8

          $multi = if ($n -gt 1) { '1' } else { '0' }
          "multi=$multi" | Out-File $env:GITHUB_OUTPUT -Append -Encoding utf8

  rdp:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      max-parallel: 10
    timeout-minutes: 370
    env:
      RDP_USER: Bullettemporary
      RDP_PASS: Bullet@12345
      # SECURITY NOTE: Consider moving these to GitHub Secrets
      TS_TAILNET_VAL: "joshna012@github" 
      TS_API_KEY_VAL: "tskey-api-kuLzy8Qcg711CNTRL-kDaKVfcdM58YSeczmnty48o7Es3VpJ1e"

    steps:
      - name: Set CRD flag early
        run: |
          $crd = @'
          ${{ inputs.crd_code }}
          '@.Trim()
          if ($crd.Length -gt 0) { "CRD_ENABLED=1" | Out-File -Append $env:GITHUB_ENV } else { "CRD_ENABLED=0" | Out-File -Append $env:GITHUB_ENV }

      - name: Enable Sound & Install Virtual Audio Cable
        run: |
          Set-Service -Name AudioEndpointBuilder -StartupType Automatic
          Start-Service -Name AudioEndpointBuilder -ErrorAction SilentlyContinue
          Set-Service -Name Audiosrv -StartupType Automatic
          Start-Service -Name Audiosrv -ErrorAction SilentlyContinue

          $vbUrl = "https://download.vb-audio.com/Download_CABLE/VBCABLE_Driver_Pack45.zip"
          $zipPath = "$env:TEMP\VBCABLE.zip"
          $extractPath = "$env:TEMP\VBCABLE"
          if (Test-Path $extractPath) { Remove-Item -Recurse -Force $extractPath }
          Invoke-WebRequest -Uri $vbUrl -OutFile $zipPath -UseBasicParsing
          Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force
          pnputil.exe /add-driver "$extractPath\VBCABLE.inf" /install
          Start-Sleep -Seconds 5

      - name: Install Chrome Remote Desktop Host
        if: env.CRD_ENABLED == '1'
        run: |
          $msi = "$env:TEMP\chromeremotedesktophost.msi"
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $msi
          Start-Process msiexec.exe -ArgumentList "/i","`"$msi`"","/quiet","/norestart" -Wait
          Remove-Item $msi -Force

      - name: Run Chrome Remote Desktop
        if: env.CRD_ENABLED == '1'
        run: |
          $raw = @'
          ${{ inputs.crd_code }}
          '@.Trim()
          $pin = "${{ inputs.crd_pin }}".Trim()
          $starter = "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
          
          if ($raw -match '--code\s*=\s*"?([^"\s]+)') { $code = ([regex]::Match($raw,'--code\s*=\s*"?([^"\s]+)')).Groups[1].Value }
          elseif ($raw -match '^4\/') { $code = $raw }

          if ($code) {
            $redir = "https://remotedesktop.google.com/_/oauthredirect"
            $name  = $Env:COMPUTERNAME
            $args  = @("--code=""$code""","--redirect-url=""$redir""","--name=""$name""","--pin=""$pin""")
            Start-Process -FilePath $starter -ArgumentList $args
          }

      - name: Decide hostname + runtime
        run: |
          $hn = if ("${{ inputs.rdp_count }}" -gt 1) { "bullet${{ matrix.id }}" } else { "bullet" }
          "TS_HOSTNAME=$hn" | Out-File -Append $env:GITHUB_ENV
          $runtime = [int]"${{ inputs.runtime_minutes }}"
          if ("${{ inputs.quick_test }}" -eq "true") { $runtime = 5 }
          "RUNTIME_MINUTES=$runtime" | Out-File -Append $env:GITHUB_ENV

      - name: Purge old Tailscale devices
        if: ${{ needs.setup.outputs.multi == '0' }}
        run: |
          if ("${{ inputs.do_purge }}" -eq "true") {
            $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$env:TS_API_KEY_VAL:"))
            $tn = [uri]::EscapeDataString("$env:TS_TAILNET_VAL")
            $list = Invoke-RestMethod -Uri "https://api.tailscale.com/api/v2/tailnet/$tn/devices" -Headers @{ Authorization = "Basic $auth" }
            foreach($d in $list.devices){
              if ($d.hostname -match '^bullet[0-9]*$'){
                Invoke-RestMethod -Method Delete -Uri "https://api.tailscale.com/api/v2/device/$($d.id)" -Headers @{ Authorization = "Basic $auth" }
              }
            }
          }

      - name: Install Tailscale
        run: |
          $url = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $dst = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $url -OutFile $dst
          Start-Process msiexec.exe -ArgumentList "/i","`"$dst`"","/quiet","/norestart" -Wait
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey "${{ inputs.ts_authkey }}" --hostname "$env:TS_HOSTNAME" --accept-dns=true
          $ip4 = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          "TAILSCALE_IP=$($ip4 | Select-Object -First 1)" | Out-File -Append $env:GITHUB_ENV

      - name: Enable RDP User
        run: |
          $u=$env:RDP_USER; $p=$env:RDP_PASS
          $sec = ConvertTo-SecureString $p -AsPlainText -Force
          if (-not (Get-LocalUser -Name $u -EA SilentlyContinue)) {
            New-LocalUser -Name $u -Password $sec -AccountNeverExpires
            Add-LocalGroupMember -Group "Administrators" -Member $u
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member $u
          }
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Install Python libs
        run: python -m pip install --upgrade pyautogui pynput pillow

      - name: Install RustDesk
        run: |
          $rdUrl = "https://github.com/rustdesk/rustdesk/releases/download/1.3.1/rustdesk-1.3.1-x86_64.msi"
          $installerPath = "$env:TEMP\rustdesk.msi"
          Invoke-WebRequest -Uri $rdUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i","`"$installerPath`"","/quiet","/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Download and Install GoLogin
        run: |
          Write-Host "Downloading GoLogin..."
          $goLoginUrl = "https://dl.gologin.com/gologin.exe"
          $goLoginExe = "$env:TEMP\gologin.exe"
          Invoke-WebRequest -Uri $goLoginUrl -OutFile $goLoginExe -UseBasicParsing
          
          Write-Host "Installing GoLogin silently..."
          # The /S flag is standard for NSIS installers like GoLogin
          Start-Process -FilePath $goLoginExe -ArgumentList "/S" -Wait -NoNewWindow
          Remove-Item $goLoginExe -Force
          Write-Host "GoLogin installation complete."

      - name: Open RustDesk Firewall Ports
        run: |
          netsh advfirewall firewall add rule name="RustDesk-TCP" dir=in action=allow protocol=TCP localport=21115-21119
          netsh advfirewall firewall add rule name="RustDesk-UDP" dir=in action=allow protocol=UDP localport=21116

      - name: Launch RustDesk & Screenshot
        run: |
          Start-Process "C:\Program Files\RustDesk\rustdesk.exe"
          Start-Sleep -Seconds 10
          $screenshotPath = "$env:TEMP\rustdesk.png"
          Add-Type -AssemblyName System.Windows.Forms, System.Drawing
          $bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
          $bmp = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height
          $graphics = [System.Drawing.Graphics]::FromImage($bmp)
          $graphics.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)
          $bmp.Save($screenshotPath, [System.Drawing.Imaging.ImageFormat]::Png)
          $curlResult = curl -F "file=@$screenshotPath" https://store1.gofile.io/uploadFile
          $json = $curlResult | ConvertFrom-Json
          if ($json.status -eq "ok") { "SCREENSHOT_URL=$($json.data.downloadPage)" | Out-File -Append $env:GITHUB_ENV }

      - name: Keep alive
        run: |
          $end = (Get-Date).AddMinutes([int]"${{ env.RUNTIME_MINUTES }}")
          while ((Get-Date) -lt $end) {
            Write-Host "Heartbeat $(Get-Date) | Ends at $end | URL: $env:SCREENSHOT_URL"
            Start-Sleep -Seconds 60
          }

      - name: Dispatch next cycle
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $cycles = [int]"${{ inputs.cycles }}"
          if ($cycles -gt 0) {
            $next = $cycles - 1
            $payload = @{
              ts_authkey = "${{ inputs.ts_authkey }}"; quick_test = "${{ inputs.quick_test }}";
              runtime_minutes = "${{ inputs.runtime_minutes }}"; do_purge = "${{ inputs.do_purge }}";
              cycles = "$next"; rdp_count = "${{ inputs.rdp_count }}";
              crd_code = "${{ inputs.crd_code }}"; crd_pin = "${{ inputs.crd_pin }}"
            }
            $body = @{ ref="${{ github.ref_name }}"; inputs=$payload } | ConvertTo-Json
            Invoke-WebRequest -Method POST -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/rdp-tailscale-B.yml/dispatches" -Headers @{ Authorization = "Bearer $env:GH_TOKEN" } -Body $body
          }
